# Generated by Django 2.2.7 on 2019-11-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxcricket', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boxcricket.Game'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.IntegerField()),
                ('bowl_number', models.IntegerField()),
                ('bowler', models.CharField(max_length=50, unique=True)),
                ('bastman', models.CharField(max_length=50, unique=True)),
                ('runs', models.IntegerField()),
                ('wicket', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxcricket.Game')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50, unique=True)),
                ('runs_scored', models.IntegerField()),
                ('runs_conceded', models.IntegerField()),
                ('wicket', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxcricket.Game')),
            ],
        ),
    ]
