# Generated by Django 2.2.7 on 2019-11-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxcricket', '0003_auto_20191123_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchscore',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='game_id',
            new_name='game',
        ),
    ]
