# Generated by Django 2.2.7 on 2019-11-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcricket', '0004_auto_20191123_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
    ]
