# Generated by Django 2.2.7 on 2019-11-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxcricket', '0005_auto_20191124_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
